### ISSUE TITLE
编码错误，输出文件为空

### ISSUE THREAD

**Issue by arrowarrow123** [olixu/cloudflare-ip-ping#1]
1. 编码出错为：（已经将input.txt编码格式改为utf-8了）
  File "pingip.py", line 38, in ping_host
    res = popen.stdout.read().decode('utf-8').strip('\n')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 0: invalid
start byte

改为
    res = popen.stdout.read().decode('utf-8', 'ignore').strip('\n')

run起来后输出是空文件。

**Comment by xwysun** [comment]
也是这个问题，不知道作者会不会修复

**Comment by olixu** [comment]
> 也是这个问题，不知道作者会不会修复

If you are using windows, please change the code of line 38  to 
 `res = popen.stdout.read().decode('gbk').strip('\n')`

I will change it later. Thanks.

**Comment by olixu** [comment]
I have tested the script on Windows 10, It failed.
If you are using Windows, Please change the line 38 to
`res = popen.stdout.read().decode('gbk').strip('\n')`

change the line 40,41,42 to
```        
if "Average" in res:
    try:
        x = re.findall("Average = ...ms", res)[0]
```

And then you will get the desired ips, Have fun!

**Comment by olixu** [comment]
当前的版本在Windows上使用已经不存在编码问题了，在linux上使用的话，请查看历史版本。

注意：中文版和英文版有区别，需要改程序。

**Comment by tsinit2001** [comment]
WIN7 64位 中文系統，依然會出現輸出爲空的狀況。
