### ISSUE TITLE
ModuleNotFoundError: No module named "msvcrt"

### ISSUE THREAD

**Issue by noyyyy** [olixu/cloudflare-ip-ping#10]
我用的使Deepin Linux, 查了下, 这个模块好像是Windows特有的, 所以意味着其他平台用不了......

**Comment by olixu** [comment]
本项目一开始是在linux（Manjaro发行版）上开发的，英文环境，所以linux完全可用，请查看历史commit

[commit](https://github.com/olixu/cloudflare-ip-ping/tree/d881e019d68f453375c14f5fb9617f3d5f4db7c4)

**Comment by noyyyy** [comment]
好的, 谢谢您, 不过好像无法生成ping_host.log. 不过在此期间, 我发现了linux可用的叫[fping](https://github.com/schweikert/fping) 的工具, 可以直接ping CIDR 地址, 暂时的解决了我的问题. 我稍微会一点python, 过几天有空了改改linux下的文件. 这个项目接受增加一个linux版py文件的pr吗

**Comment by olixu** [comment]
您有空的话可以将本仓库中最新的commit改写成linux版的，风格最好要统一，需要改的地方比较少，我本地不是很方便测试，欢迎PR，我会新建一个Linux分支，使用中文的环境吧 。谢谢。
