### ISSUE TITLE
求问大佬这些ip怎么获取的

### ISSUE THREAD

**Issue by LimitBreaker01** [olixu/cloudflare-ip-ping#12]
第一次使用时，得到一个39ms的ip，等到后面越来越延迟高，普遍40ms-42ms的ip，请教大佬，这些ip怎么获取来的
本人移动100M宽带。看hostloc论坛里有些移动的也能跑8万甚至10万的油管，我运气最高只能到3万左右。
有什么好的方法及建议吗，求大佬明示，在此感谢大佬了

**Comment by olixu** [comment]
对于你的第一个问题，我不知道你说的"这些ip怎么获取来的"是想说什么意思，40ms的延迟可以了，已经很低了。
移动100M可以上个软路由，肯定能跑满（用了软路由你会发现新世界的，真的比Windows快多了，至少我本地不用软路由只能跑0.2万，用了软路由，跑满100M），你说的这个论坛我不是很清楚。

**Comment by LimitBreaker01** [comment]
这些ip就是input.txt里面所有的ip，大佬后续还会更新吗？还是这些ip就是最好的了。本人的宽带是国内移动的。基本上就得两天扫描更换一次ip才可以跑满并且不断流。就大佬提出的更换软路由，比如软件层面换什么软件好，或者我手里路由直接刷固件更好解决这一问题？再次感谢大佬热心回复

**Comment by olixu** [comment]
input.txt是从[](https://www.cloudflare.com/ips/)获取的，不用更新，这里已经是几百万个IP了，足够用的。

移动可以尝试直接使用1.0.0.0这个IP，我一直用的就是这个，不需要变换。

我是用的一台古老台式机当的旁路由，用之前我一直不相信软路由有那么大的效果，用了以后才发现无敌了。具体原因我怀疑是windows和linux内核对网络流控的管理差异（我没验证过，至今不知道具体原因，我还没看到有人能解释清楚，可能得去问开发者）

**Comment by olixu** [comment]
> 这些ip就是input.txt里面所有的ip，大佬后续还会更新吗？还是这些ip就是最好的了。本人的宽带是国内移动的。基本上就得两天扫描更换一次ip才可以跑满并且不断流。就大佬提出的更换软路由，比如软件层面换什么软件好，或者我手里路由直接刷固件更好解决这一问题？再次感谢大佬热心回复

软路由可以去TB或者PDD买一个，买一个性能好一点的，不超过500元，最垃圾的就是N1盒子了
