### ISSUE TITLE
大佬能不能增加一个排序

### ISSUE THREAD

**Issue by kbnq** [olixu/cloudflare-ip-ping#13]
输出一个Excel工作表也行，这样方便更快找到合适的ip，感谢。

**Comment by olixu** [comment]
你想要加上什么排序算法，现在是使用的按照ping延迟排序，然后按照丢包排序，txt文件中，从上往下应该是越来越好的

**Comment by tianshi1987** [comment]
我觉得挺好用的，虽然我现在移动1000M，也只能跑到5-6W哈哈，不过其实够了。2W就足够4K了
