### ISSUE TITLE
发现你和我的项目撞车了😂... Github 推荐给我的 Explore 里看到的。

### ISSUE THREAD

**Issue by XIU2** [olixu/cloudflare-ip-ping#14]
在 Github 的海洋里不知道有多少项目撞车了，有需求的时候怎么搜也搜不到，自己造出来后发现又重复造轮子了。。。  

* **https://github.com/XIU2/CloudflareSpeedTest**  
_🌩 测试 Cloudflare CDN 延迟和速度，获取最快 IP (IPv4+IPv6)！_  

> 看了下，咱们两个的项目都差不多，我这只多了个 **Cloudflare IP 测试下载速度**的功能。  

同类项目 互相交流~ 虽然我对 Python 不熟...

**Comment by olixu** [comment]
撞车正常，go应该要比python的性能强多了。
两年前查了github上没找到这样的库，所以就自己写了一下，当时也是为了自己那方面的需求，不过好像现在用的人还挺多的，主要还是cloudflare财大气粗，哈哈哈哈。
😃

**Comment by olixu** [comment]
> 在 Github 的海洋里不知道有多少项目撞车了，有需求的时候怎么搜也搜不到，自己造出来后发现又重复造轮子了。。。
> 
> https://github.com/XIU2/CloudflareSpeedTest
> 同类项目 互相交流~ 虽然我对 Python 不熟...

欢迎多交流交流，我搞强化学习的 🤝

**Comment by MoshiCoCo** [comment]
> 撞车正常，go应该要比python的性能强多了。
> 两年前查了github上没找到这样的库，所以就自己写了一下，当时也是为了自己那方面的需求，不过好像现在用的人还挺多的，主要还是cloudflare财大气粗，哈哈哈哈。
> 😃

为了自己那方面的需求 啊 这，我想歪了

**Comment by olixu** [comment]
> > 撞车正常，go应该要比python的性能强多了。
> > 两年前查了github上没找到这样的库，所以就自己写了一下，当时也是为了自己那方面的需求，不过好像现在用的人还挺多的，主要还是cloudflare财大气粗，哈哈哈哈。
> > 😃
> 
> 为了自己那方面的需求 啊 这，我想歪了

6
