### ISSUE TITLE
”没有找到合适的IP，请调整阈值“为什么会这样？

### ISSUE THREAD

**Issue by fxzxmic** [olixu/cloudflare-ip-ping#15]
本地运行的时候没有找到任何一个IP，这是为什么啊，我自己测试了几个，ping值都在170-210之间。

**Comment by olixu** [comment]
阈值设置的多少呢？
可以先将阈值设置的大一点，例如设置到300，来验证程序是否运行正常。

**Comment by fxzxmic** [comment]
100 200 都试了，300程序会出错，299也试了，都是这样。

**Comment by fxzxmic** [comment]
是不是程序需要中文命令行环境？我的命令行是英文的。

**Comment by olixu** [comment]
是的

**Comment by fxzxmic** [comment]
好吧

**Comment by olixu** [comment]
请看中文说明中的运行环境，英文环境的Linux系统也是可以用的，可以找一下历史的commit，程序一开始我是在英文环境linux上开发的。

**Comment by fxzxmic** [comment]
[pingip.zip](https://github.com/olixu/cloudflare-ip-ping/files/5555291/pingip.zip)

英文命令行的可执行程序，而且其实此程序没有主动使用管理员运行的必要，所以我删了，有必要的话右键菜单使用管理员身份运行。
