### ISSUE TITLE
IP范围太小只有x.x.x.15

### ISSUE THREAD

**Issue by dotDuck** [olixu/cloudflare-ip-ping#3]
感谢开发nice的小工具，使用有效而且很方便！
有一点疑问：
IP范围是否有问题？看到IP列表里面不同网段只有x.x.x.15这一个IP地址
有一点建议：
可以考虑加入测速功能，现在只是测试了延迟和丢包，但是下载文件速度没有测试。当然最主要的还是延迟和丢包。
再次感谢！

**Comment by olixu** [comment]
第一点：对于不同的网段，只选择x.x.x.15的确是有局限性，但是增加测试ip的数量会相应的增加测试时间，这对于很多用户来说可能体验会下降。一两分钟测试出结果应该还是可以接受的，但是5，6分钟的话可能我自己都接受不了。

第二点：对于测速功能，我个人认为其实没有什么必要，同第一点，时间越长，用户体验越差，不过非常欢迎你PR，若效果合适的话，我会合并，非常感谢。

PS：能反馈下你的：

你的运营商（移动联通电信）

你的所在地区

你的运行结果

找到的ip能够用多久

晚高峰速度怎么样

欢迎分享！非常感谢。

**Comment by dotDuck** [comment]
第一点也确实是个不错的解决方案，相当于探测了网段速度，如果需要拓展IP可以自行设置再测即可，毕竟筛选时间也很重要尤其是在IP质量经常变化的情况下。
反馈没有问题，运行结果需要整个文件吗还是列出几个高质量IP即可？
之前另一台Win10 x64 PC上运行的，结果没有保存，今天尝试在Win8.1 x64上运行，过程正常但是输出结果文件为空。使用的是release中最新的exe，希望可以解答:wink:
或者我是否可以Python直接运行？看到了issue1中有提到编码问题。

**Comment by dotDuck** [comment]
> 第一点：对于不同的网段，只选择x.x.x.15的确是有局限性，但是增加测试ip的数量会相应的增加测试时间，这对于很多用户来说可能体验会下降。一两分钟测试出结果应该还是可以接受的，但是5，6分钟的话可能我自己都接受不了。
> 
> 第二点：对于测速功能，我个人认为其实没有什么必要，同第一点，时间越长，用户体验越差，不过非常欢迎你PR，若效果合适的话，我会合并，非常感谢。
> 
> PS：能反馈下你的：
> 
> 你的运营商（移动联通电信）
> 
> 你的所在地区
> 
> 你的运行结果
> 
> 找到的ip能够用多久
> 
> 晚高峰速度怎么样
> 
> 欢迎分享！非常感谢。

**Comment by olixu** [comment]
有条件的话可以直接用python运行，我是在windows10 64位系统上打包的，其他系统没测试过，所以关于你的问题，我可能回答不了你，建议直接跑程序并debug。

现在仓库中的程序是可以直接运行的，安装一下必要的库，安装一下必要的库就可以了。编码问题是针对linux系统的，老版本的程序只能用linux使用，在windows上需要改编码。
