### ISSUE TITLE
輸出爲空文件

### ISSUE THREAD

**Issue by tsinit2001** [olixu/cloudflare-ip-ping#4]
最初是在WIN7 64位主機測試，輸出文件能夠生成，但是0字節。
換到WIN 10 64位來試，依然如此。
![图片](https://user-images.githubusercontent.com/67938914/86815004-ba45bc00-c0b4-11ea-8116-f287748ec498.png)

**Comment by olixu** [comment]
那可能是你的阈值设置的太小了，导致没有找到合适的IP，或者说，你的线路不合适用CF。

**Comment by tsinit2001** [comment]
河南移動家寬，閾值設置到299，依然輸出爲空。看來CF在我來說，不是加速優化，而是只能作爲救活IP來用了。。。
