### ISSUE TITLE
能否增加一项丢包的阈值设置

### ISSUE THREAD

**Issue by liamcos** [olixu/cloudflare-ip-ping#5]
从fping-msys2.0这个工具的使用经验来看，选出来速度最快的IP 延迟大都在220+ms了，如果在本工具里设置220的阈值，结果上千，里面有大量丢包75%的，再从里面找丢包少的眼睛都看花了，不妨增加一项丢包的阈值设di置，ping阈值放宽，丢包阈值严格控制，把丢包严重的IP也从结果中剔除出去。

另外关于测速功能，本工具输出的结果可以丢到fping-msys2.0这个工具里直接进行测速排序，但结果是很多丢包严重的反而下载快排在前面，而实际使用体验很差劲，如果结果里没有这些丢包严重的IP，再去测速就能减少这方面的干扰，这是希望能够增加丢包阈值设置的另一个原因，便于测速排序。

**Comment by olixu** [comment]
延迟和线路有关系，移动连接的是香港，延迟一般在40-80ms。电信联通连美西，延迟一般在200左右。

丢包阈值就不加了，直接按照阈值、延迟的顺序排序吧。

至于测速是否要用fping这个工具，我个人觉得是无需使用的。测出来的IP，直接放到浏览器中打开，如果很快的打开‘Error 1003 Ray ID: 5af5c9d5cae60e46 • 2020-07-08 00:46:28 UTC Direct IP access not allowed’，那么就基本上是可用的，用工具测速还是太慢了，找个合适的CF的IP我个人觉得所有流程加起来时间不应该超过2分钟。

**Comment by olixu** [comment]
已经更新好了，欢迎测试。
