### ISSUE TITLE
請問能不能出一個能容忍超級慢線路的版本。

### ISSUE THREAD

**Issue by tsinit2001** [olixu/cloudflare-ip-ping#8]
我用的是爛線，有個常用的VPS的IP地址死掉了。想找各最能容忍的線路。
目前的版本，閾值最大範圍是299，請問能不能有2999或者29999的版本啊？
目的是找到一個延遲很嚴重，但仍然能救活IP的CF地址。

順便說，新的版本在檢測不到內容的時候，會提示“没有找到合适的IP，请调整阈值“，看起來安心多了。謝謝這個體貼的更新。

**Comment by olixu** [comment]
有条件的话可以直接跑python程序，可以自己在代码中修改一下参数。

**Comment by tsinit2001** [comment]
哈，您太看得起我這菜雞了。。。
