### ISSUE TITLE
输出文件为空(没有找到合适的IP，请调整阈值)

### ISSUE THREAD

**Issue by dotDuck** [olixu/cloudflare-ip-ping#9]
Hi, 我又来了，我只是想反馈一下运行结果，又发现了问题。
WIN8.1 x64，cmd使用python运行，两个问题。

1. 输出格式混乱
![001](https://user-images.githubusercontent.com/3467621/86911542-14469000-c14e-11ea-8ad8-df1e70847480.png)

2. 输出结果为空，线程100阈值200、线程200阈值100均有测试，我实际的网络是没问题的，拿我之前测试的一个结果手动ping如下
![002](https://user-images.githubusercontent.com/3467621/86911695-51ab1d80-c14e-11ea-8deb-d53d70990a45.png)

**Comment by dotDuck** [comment]
- 问题2找到了原因，Windows的ping不支持`-c`参数，而是使用`-n`，修改了脚本指定`-n 10`，时间有点长用了10分钟多。时间敏感的话还是可以指定作者默认的`-n 1`，详见[Windows ping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping) 
至于WIN10可以，可能是因为WIN10的ping指令做了参数兼容。
结果sort好评!不用再自己用excel排序了...

- 结果反馈
你的运营商（移动）
你的所在地区（西南，不具体说明）
你的运行结果（随机5条IP 104.19.23.15, 延迟:35ms, 丢包:0%/104.19.16.15, 延迟:36ms, 丢包:0%/162.159.129.15, 延迟:37ms, 丢包:0%/172.65.210.15, 延迟:38ms, 丢包:0%/104.19.233.15, 延迟:39ms, 丢包:0%）
找到的ip能够用多久（待定）
晚高峰速度怎么样（待定）

**Comment by olixu** [comment]
非常感谢您的issue，-c是项目初期我在linuxs上 开发的时候使用的命令，现在改到了windows上，我忘记改了，经过测试，我就直接删除-c命令了。

**Comment by olixu** [comment]
https://github.com/olixu/cloudflare-ip-ping/releases/tag/V4.0.0

已经更新好了，欢迎在Windows8系统进行测试，非常感谢！

**Comment by dotDuck** [comment]
> https://github.com/olixu/cloudflare-ip-ping/releases/tag/V4.0.0
> 
> 已经更新好了，欢迎在Windows8系统进行测试，非常感谢！

WIN8.1x64已测试，没有问题
